package CampusServerCorba;

/**
 * CampusServerCorba/CampusServerInterfaceHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from CampusServerCorba.idl
 * Saturday, November 4, 2017 12:14:30 o'clock PM EDT
 */

public final class CampusServerInterfaceHolder implements org.omg.CORBA.portable.Streamable {
    public CampusServerCorba.CampusServerInterface value = null;

    public CampusServerInterfaceHolder() {
    }

    public CampusServerInterfaceHolder(CampusServerCorba.CampusServerInterface initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = CampusServerCorba.CampusServerInterfaceHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        CampusServerCorba.CampusServerInterfaceHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return CampusServerCorba.CampusServerInterfaceHelper.type();
    }

}
