package CampusServerCorba;


/**
 * CampusServerCorba/CampusServerInterface.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from CampusServerCorba.idl
 * Saturday, November 4, 2017 12:14:30 o'clock PM EDT
 */

public interface CampusServerInterface extends CampusServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface CampusServerInterface
