package CampusServerCorba;


/**
 * CampusServerCorba/CampusServerInterfaceOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from CampusServerCorba.idl
 * Saturday, November 4, 2017 12:14:30 o'clock PM EDT
 */

public interface CampusServerInterfaceOperations {
    int getUdpPort();

    String createRoom(String json);

    String deleteRoom(String json);

    String bookRoom(String json);

    String switchRoom(String json);

    String getAvailableTimeSlotCount(String json);

    String getAvailableTimeSlotByRoom(String json);

    String cancelBooking(String json);

    boolean checkAdminId(String json);
} // interface CampusServerInterfaceOperations
