package service.server.CampusServerCorba;


/**
 * service.server.CampusServerCorba/CampusServerInterfaceOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from service.server.CampusServerCorba.idl
 * Saturday, November 4, 2017 12:26:15 o'clock AM EDT
 */

public interface CampusServerInterfaceOperations {
    int add(int a, int b);

    String createRoom(String json);

    String deleteRoom(String json);

    String bookRoom(String json);

    String switchRoom(String json);

    String getAvailableTimeSlotCount(String json);

    String getAvailableTimeSlotByRoom(String json);

    String cancelBooking(String json);

    String checkAdminId(String json);
} // interface CampusServerInterfaceOperations
