package service.server.CampusServerCorba;


/**
 * service.server.CampusServerCorba/CampusServerInterface.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from service.server.CampusServerCorba.idl
 * Saturday, November 4, 2017 12:26:15 o'clock AM EDT
 */

public interface CampusServerInterface extends CampusServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface CampusServerInterface
