package service.server.CampusServerCorba;

/**
 * service.server.CampusServerCorba/CampusServerInterfaceHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from service.server.CampusServerCorba.idl
 * Saturday, November 4, 2017 12:26:15 o'clock AM EDT
 */

public final class CampusServerInterfaceHolder implements org.omg.CORBA.portable.Streamable {
    public service.server.CampusServerCorba.CampusServerInterface value = null;

    public CampusServerInterfaceHolder() {
    }

    public CampusServerInterfaceHolder(service.server.CampusServerCorba.CampusServerInterface initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = service.server.CampusServerCorba.CampusServerInterfaceHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        service.server.CampusServerCorba.CampusServerInterfaceHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return service.server.CampusServerCorba.CampusServerInterfaceHelper.type();
    }

}
