package service.server.CampusServerCorba;


/**
 * service.server.CampusServerCorba/CampusServerInterfaceHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from service.server.CampusServerCorba.idl
 * Saturday, November 4, 2017 12:26:15 o'clock AM EDT
 */

abstract public class CampusServerInterfaceHelper {
    private static String _id = "IDL:service.server.CampusServerCorba/CampusServerInterface:1.0";

    public static void insert(org.omg.CORBA.Any a, service.server.CampusServerCorba.CampusServerInterface that) {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static service.server.CampusServerCorba.CampusServerInterface extract(org.omg.CORBA.Any a) {
        return read(a.create_input_stream());
    }

    private static org.omg.CORBA.TypeCode __typeCode = null;

    synchronized public static org.omg.CORBA.TypeCode type() {
        if (__typeCode == null) {
            __typeCode = org.omg.CORBA.ORB.init().create_interface_tc(service.server.CampusServerCorba.CampusServerInterfaceHelper.id(), "CampusServerInterface");
        }
        return __typeCode;
    }

    public static String id() {
        return _id;
    }

    public static service.server.CampusServerCorba.CampusServerInterface read(org.omg.CORBA.portable.InputStream istream) {
        return narrow(istream.read_Object(_CampusServerInterfaceStub.class));
    }

    public static void write(org.omg.CORBA.portable.OutputStream ostream, service.server.CampusServerCorba.CampusServerInterface value) {
        ostream.write_Object(value);
    }

    public static service.server.CampusServerCorba.CampusServerInterface narrow(org.omg.CORBA.Object obj) {
        if (obj == null)
            return null;
        else if (obj instanceof service.server.CampusServerCorba.CampusServerInterface)
            return (service.server.CampusServerCorba.CampusServerInterface) obj;
        else if (!obj._is_a(id()))
            throw new org.omg.CORBA.BAD_PARAM();
        else {
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            service.server.CampusServerCorba._CampusServerInterfaceStub stub = new service.server.CampusServerCorba._CampusServerInterfaceStub();
            stub._set_delegate(delegate);
            return stub;
        }
    }

    public static service.server.CampusServerCorba.CampusServerInterface unchecked_narrow(org.omg.CORBA.Object obj) {
        if (obj == null)
            return null;
        else if (obj instanceof service.server.CampusServerCorba.CampusServerInterface)
            return (service.server.CampusServerCorba.CampusServerInterface) obj;
        else {
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            service.server.CampusServerCorba._CampusServerInterfaceStub stub = new service.server.CampusServerCorba._CampusServerInterfaceStub();
            stub._set_delegate(delegate);
            return stub;
        }
    }

}
